from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
CPPPATH = [cwd]
objs = []

group = DefineGroup('libgprof', src, depend = ['RT_USING_GPROF', 'RT_USING_DFS'], CPPPATH = CPPPATH)

Return('objs')