# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('src/*.c') + Glob('ports/*.c')
CPPPATH = [cwd + '/inc']

group = DefineGroup('TraceAgent', src, depend = ['RT_USING_TRACE','RT_USING_DFS'], CPPPATH = CPPPATH)

Return('group')
